=== CourseOrchestra/flute/src/main/xsd/fluteconfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="config">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded" minOccurs="0">
                <xs:element name="neverstop" type="xs:boolean"/>
                <xs:element name="retrywait" type="xs:int"/>
                <xs:element name="dbconnstring"/>
                <xs:element name="dbuser"/>
                <xs:element name="dbpassword"/>
                <xs:element name="redishost"/>
                <xs:element name="redisport" type="xs:int"/>
                <xs:element name="redispassword"/>
                <xs:element name="exposeredis" type="xs:boolean"/>
                <xs:element name="scorepath"/>
                <xs:element name="pylibpath"/>
                <xs:element name="javalibpath"/>
                <xs:element name="loglogins" type="xs:boolean"/>
                <xs:element name="fluteuserid"/>
                <xs:element name="skipdbupdate" type="xs:boolean"/>
                <xs:element name="forcedbinitialize" type="xs:boolean"/>
                <xs:element name="celestaproperties"/>
                <xs:element name="resthost"/>
                <xs:element name="restport" type="xs:int"/>
                <xs:element name="resttimeout" type="xs:int"/>
                <xs:element name="dbtable">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded" minOccurs="0">
                            <xs:group ref="taskSourceElements"/>
                            <xs:element name="tablename"/>
                            <xs:element name="pollingperiod" type="xs:int"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="redisqueue">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded" minOccurs="0">
                            <xs:group ref="taskSourceElements"/>
                            <xs:element name="queuename"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="scheduledtask">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded" minOccurs="0">
                            <xs:group ref="taskSourceElements"/>
                            <xs:element name="schedule"/>
                            <xs:element name="script" type="scriptName"/>
                            <xs:element name="params"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
                <xs:element name="looptask">
                    <xs:complexType>
                        <xs:choice maxOccurs="unbounded" minOccurs="0">
                            <xs:element name="script" type="scriptName"/>
                            <xs:element name="params"/>
                            <xs:element name="waitonsuccess" type="xs:int"/>
                            <xs:element name="waitonfailure" type="xs:int"/>
                            <xs:element name="finalizer" type="scriptName"/>
                            <xs:element name="count" type="xs:int"/>
                        </xs:choice>
                    </xs:complexType>
                </xs:element>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:group name="taskSourceElements">
        <xs:choice>
            <xs:element name="maxthreads" type="xs:int"/>
            <xs:element name="terminationtimeout" type="xs:int"/>
            <xs:element name="finalizer" type="scriptName"/>
        </xs:choice>
    </xs:group>
    <xs:simpleType name="scriptName">
        <xs:restriction base="xs:string">
            <xs:pattern value="([A-Za-z][A-Za-z0-9]*)(\.[A-Za-z_]\w*)+"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== CourseOrchestra/flute/src/test/resources/ru/curs/flute/badTestSetup.xml
<?xml version="1.0" encoding="utf-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="http://corchestra.ru/schema/fluteconfig.xsd">
    <dbconnstring>jdbc:postgresql://127.0.0.1:5432/celesta</dbconnstring>
    <dbuser>postgres</dbuser>
    <dbpassword>123</dbpassword>
    <redishost>localhost</redishost>
    <redisport>6379</redisport>
    <neverstop>false</neverstop>
    <retrywait>50000</retrywait>
    <scorepath>D:/score</scorepath>
    <resthost>127.0.0.1</resthost>
    <restport>12345</restport>
    <resttimeout>360</resttimeout>
    <pylibpath>D:/jython2.7.0/Lib</pylibpath>
    <looptask>
        <script>foo.hello.run</script>
        <waitonsuccess>1000</waitonsuccess>
        <waitonfailure>30000</waitonfailure>
        <count>1</count>
        <finalizer>ru.curs.flute.Hello#stop</finalizer>
    </looptask>
</config>
